---
- name: Update package cache
  ansible.builtin.import_role:
    name: ansible.tutorial.package_cache
    
- name: Install package
  ansible.builtin.package:
    name: "{{ package_name }}"
    state: present
  become: true
