---
- name: Install neofetch
  hosts: lxc
  gather_facts: false

  tasks:
    - name: Install neofetch
      ansible.builtin.import_role:
        name: ansible.tutorial.package
      vars: 
        package_name: neofetch
